language: rust
rust:
  - 1.22.0
  - 1.26.0
  - stable
  - beta
  - nightly
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
notifications:
  email:
    on_success: never
branches:
  only:
    - master