[package]
authors = ["o2sh <ossama-hjaji@live.fr>"]
description = "Adds one to a number"
license = "MIT"
name = "add-one"
readme = "README.md"
repository = "https://github.com/o2sh/add-one"
version = "1.0.0"
